### PR TITLE
Update ru pokemon names

### PR DESCRIPTION
**Pull request by 102**
This is quite questionable PR with pokemon names from [wikipedia article](https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BF%D0%BE%D0%BA%D0%B5%D0%BC%D0%BE%D0%BD%D0%BE%D0%B2).

This names are also used there:
1. http://ilovepokemongo.ru/pokedex
2. http://pokemongolife.ru/pokemony/

// @zverbeta @sindresorhus what do you think about this?

### CODE REVIEW

**Comment by zverbeta** [comment]
Hey there. 

@102 Some pokemon name need to check the grammar of russian, for example this name https://github.com/sindresorhus/pokemon/pull/26/commits/a890ff4566045adee8c2d90d24dc09a9aacd686d#diff-39f11be5bf60a0b4a2f85744004d2f43L116 
Or 
https://github.com/sindresorhus/pokemon/pull/26/commits/a890ff4566045adee8c2d90d24dc09a9aacd686d#diff-39f11be5bf60a0b4a2f85744004d2f43L134

**Comment by 102** [comment]
@zverbeta well, that's correct, some names are still have wrong spelling (have fixed more in the last commit)

**Comment by 102** [comment]
@zverbeta there's no consistent naming strategy even in single article at wikipedia, will try to find more reliable source

**Comment by 102** [comment]
@zverbeta what do you think about this now?

**Comment by zverbeta** [comment]
Looks good :)

**Comment by sindresorhus** [comment]
Thank you! @102 Any chance you could help out with https://github.com/sindresorhus/pokemon/pull/24? It's blocked on Russian names.

**Comment by 102** [comment]
@sindresorhus sure, I'll take a look

**Pull request merged**
