### PR TITLE
Update en.json

### PR DESCRIPTION
**Pull request by MohamedAlFahim**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you link to the source of this pokemon? It also needs to be added to the localizations.

**Comment by MohamedAlFahim** [comment]
@sindresorhus I am not exactly sure what you mean by localizations. However, the sources are:

- https://www.serebii.net/pokedex-sm/806.shtml
- https://www.serebii.net/pokedex-sm/805.shtml (**Note:** Stakataka is also a valid name)

**Comment by sindresorhus** [comment]
The name needs to be added in these languages too: https://github.com/sindresorhus/pokemon/tree/master/data

**Comment by sindresorhus** [comment]
Closing for lack of activity.

**Pull request closed without merging**
