### PR TITLE
Added Wyrdeer and Basculegion

### PR DESCRIPTION
**Pull request by Aatmaj-Zephyr**
Added last 2 pokemon from the list at https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_National_Pok%C3%A9dex_number

### CODE REVIEW

**Review by Aatmaj-Zephyr — COMMENTED** [review]
Added two words

**Comment by Aatmaj-Zephyr** [comment]
More links- 
https://bulbapedia.bulbagarden.net/wiki/Basculegion_(Pok%C3%A9mon)
https://bulbapedia.bulbagarden.net/wiki/Wyrdeer_(Pok%C3%A9mon)

**Comment by sindresorhus** [comment]
I don't think it makes sense to add them yet since they don't have a number ID.

**Comment by Aatmaj-Zephyr** [comment]
Sure. They can be added when they do get it!

**Pull request closed without merging**
