### PR TITLE
move json files to data directory - fixes #14

### LINKED ISSUE #14: Move json files to directory
I think it might be cleaner if we moved the json files in a subdirectory.

```
pokemon
   |- en.json
   |- fr.json
   |- ...
```

### PR DESCRIPTION
**Pull request by SamVerschueren**
Fixes #14. 

Wanted to rename all the files to lower case (e.g. `zh-hans.json`, `zh-hant.json`) and call `toLowerCase()` in the require because clinton fails on these. But up to you if you want that.

```
  data/zh-Hans.json
  ✖  Filename is not in kebab case. Rename it to zh-hans.json.  filename-case

  data/zh-Hant.json
  ✖  Filename is not in kebab case. Rename it to zh-hant.json.  filename-case

  2  errors
```

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Wanted to rename all the files to lower case (e.g. zh-hans.json, zh-hant.json) and call toLowerCase() in the require because clinton fails on these. But up to you if you want that.

Sure

**Comment by SamVerschueren** [comment]
Fixed

**Comment by sindresorhus** [comment]
You need to update `files` in package.json too.

**Comment by SamVerschueren** [comment]
Nice catch!

**Comment by sindresorhus** [comment]
👍

**Pull request merged**
