### PR TITLE
add gen8 data except russian

### PR DESCRIPTION
**Pull request by zjxs1997**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why "except russian"?

**Comment by zjxs1997** [comment]
> Why "except russian"?

I couldn't find reliable russian data that time, would search for it if time permits

**Comment by sindresorhus** [comment]
https://bulbapedia.bulbagarden.net/wiki/User:Raltseye/List_of_Russian_Pok%C3%A9mon_names#Generation_VIII

**Comment by TheBeardedGaul** [comment]
No one to validate this PR ?

**Comment by sindresorhus** [comment]
Closing for lack of activity.

**Pull request closed without merging**
